"""1_12_2017_21_52

Revision ID: 214f263e3e1a
Revises: 3a99485a5876
Create Date: 2017-12-01 21:52:33.627902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214f263e3e1a'
down_revision = '3a99485a5876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('_unique_name_for_table_uc', type_='unique')
        batch_op.create_unique_constraint('_unique_name_for_table_uc', ['product_name', 'table_id', 'price'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('_unique_name_for_table_uc', type_='unique')
        batch_op.create_unique_constraint('_unique_name_for_table_uc', ['product_name', 'table_id'])

    # ### end Alembic commands ###
