"""1_12_2017_22_54

Revision ID: 379dd7906acd
Revises: 214f263e3e1a
Create Date: 2017-12-01 22:54:36.394260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379dd7906acd'
down_revision = '214f263e3e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_product', schema=None) as batch_op:
        batch_op.alter_column('count',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_user_product_table_id_table'), 'table', ['table_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_product_table_id_table'), type_='foreignkey')
        batch_op.alter_column('count',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
