"""4_12_2017_19_9

Revision ID: 39336300a327
Revises: 379dd7906acd
Create Date: 2017-12-04 19:09:07.506324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39336300a327'
down_revision = '379dd7906acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.drop_column('table_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_info', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
