"""5_12_2017_20_33

Revision ID: d33477f8bc66
Revises: 39336300a327
Create Date: 2017-12-05 20:33:47.698170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33477f8bc66'
down_revision = '39336300a327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_product', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed', sa.Boolean(), nullable=True))
        batch_op.drop_column('price')

    with op.batch_alter_table('user_table_archive', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table_archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))
        batch_op.drop_column('closed')

    with op.batch_alter_table('user_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
